### PR TITLE
refactor: remove unused files

### PR DESCRIPTION
**Pull request by weslleycamilo**
Remove dependence of role bootstrap.

### CODE REVIEW

**Review by mtulio — COMMENTED** [review]
@weslleycamilo why do you remove the CI test file [`.travis.yml`]?

**Comment by weslleycamilo** [comment]
@mtulio  because we don't use travis and I thought it was paid :( but it looks like it is free for [GitHub Projects](https://github.com/travis-ci/travis-ci)

I'm going to revert it.

**Review by raphapr — CHANGES_REQUESTED** [review]
Does this affects the role execution? There is no need to remove unused files when we fork a project.

**Comment by weslleycamilo** [comment]
Yes @raphapr  it does affect the role execution once its requirements is not found it will break.

**Comment by mtulio** [comment]
@weslleycamilo has broken? It was 'cause the removal of `requirements.yml` ? I am quite sure, but as I remember, when you are using an role as a submodule, it does not run the `ansible-galaxy` (that uses that file), right?

**Comment by weslleycamilo** [comment]
There is no need to remove any file.

**Pull request closed without merging**
